name: Fetch and Store Uploaded Videos

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
jobs:
  fetch-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r .github/dependencies/fetch_videos_uploaded.txt
    - name: Create database table

    - name: Execute Python script
      run: python fetch_videos_uploaded.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
