name: Fetch YouTube Data

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Manual trigger

jobs:

example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
  fetch_data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scripts
        run: |
          python get_channel_info.py
          python fetch_videos_uploaded.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
