name: Fetch Uploaded Videos

on:
  workflow_dispatch:  # Manual trigger

jobs:
  fetch_uploaded_videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_videos_uploaded.py
        run: |
          python fetch_videos_uploaded.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
